db.mainusers.insertMany([
  {
    "username": "Leon Liang Tang",
    "email": "leonliangtang@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 54500,
    "level": 77,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Leon Tang",
    "email": "leontang@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 53500,
    "level": 76,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Tang Leon",
    "email": "tangleon@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 53700,
    "level": 76,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Ava Smith",
    "email": "ava.smith@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 52500,
    "level": 75,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Benjamin Johnson",
    "email": "benjamin.johnson@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 50500,
    "level": 73,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Charlotte Williams",
    "email": "charlotte.williams@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 48500,
    "level": 71,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Daniel Brown",
    "email": "daniel.brown@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 46500,
    "level": 69,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Ella Jones",
    "email": "ella.jones@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 44500,
    "level": 67,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Fiona Miller",
    "email": "fiona.miller@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 42500,
    "level": 65,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Gabriel Davis",
    "email": "gabriel.davis@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 40500,
    "level": 63,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Hannah Garcia",
    "email": "hannah.garcia@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 38500,
    "level": 61,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Isaac Martinez",
    "email": "isaac.martinez@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 36500,
    "level": 59,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Julia Rodriguez",
    "email": "julia.rodriguez@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 35900,
    "level": 58,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Kevin Wilson",
    "email": "kevin.wilson@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 35000,
    "level": 57,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Lily Anderson",
    "email": "lily.anderson@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 34300,
    "level": 56,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Mason Thomas",
    "email": "mason.thomas@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 33500,
    "level": 55,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Nora Taylor",
    "email": "nora.taylor@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 32900,
    "level": 54,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Oliver Moore",
    "email": "oliver.moore@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 32000,
    "level": 53,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Penelope Jackson",
    "email": "penelope.jackson@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 31400,
    "level": 52,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Quinn Martin",
    "email": "quinn.martin@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 30500,
    "level": 51,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Ruby Lee",
    "email": "ruby.lee@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 29800,
    "level": 50,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Samuel Perez",
    "email": "samuel.perez@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 29000,
    "level": 49,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Tessa Thompson",
    "email": "tessa.thompson@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 28300,
    "level": 48,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Uriah White",
    "email": "uriah.white@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 27500,
    "level": 47,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  },
  {
    "username": "Violet Harris",
    "email": "violet.harris@example.com",
    "password": "yoshi",
    "coins": 100000,
    "xp": 26800,
    "level": 46,
    "achievements": [],
    "subscriptionActive": false,
    "subscriptionPlan": null,
    "lastDailyClaim": null,
    "purchasedItems": [],
    "xpBoost": 1.0,
    "nameColor": null
  }
]);
