const cardTypeNames = {
  email: 'Email Message',
  modern_email: 'Email Message',
  website: 'Website',
  sms: 'SMS Message',
  app_download: 'App Download',
  qr_code: 'QR Code',
  social_media: 'Social Media Post',
  job_offer: 'Job Opportunity',
  tech_support: 'Technical Support Alert',
  document: 'Document Download',
  payment_confirmation: 'Payment Confirmation',
  security_alert: 'Security Alert',
  advertisement: 'Online Advertisement',
  browser_extension: 'Browser Extension',
  event_invitation: 'Event Invitation',
  survey: 'Survey or Quiz',
  wifi_portal: 'WiFi Login Portal',
  certificate_error: 'Security Certificate Error',
  software_update: 'Software Update',
  puzzle_game: 'Online Game',
  video_conference: 'Video Meeting Invitation',
  file_sharing: 'File Sharing Link',
  bank_notification: 'Bank Alert',
  crypto_investment: 'Crypto Investment',
  account_verification: 'Account Verification',
  lottery_winner: 'Lottery Winner',
  charity_donation: 'Charity Donation',
  package_delivery: 'Package Delivery',
  cloud_storage: 'Cloud Storage Alert',
  dating_profile: 'Dating Profile',
  review_request: 'Review Request',
  medical_alert: 'Medical Alert',
  membership_renewal: 'Membership Renewal',
  news_alert: 'News Alert',
  government_notice: 'Government Notice'
};

export default cardTypeNames;
